[connections.snowflake]
account = "DTCIWPN-CT56083"
user = "mbiswanath"
password = "Balark201$"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
